# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import sys

def main():
    #max_number=int(sys.argv[1])
    max_number=4e6
    sum = get_sum(max_number)
    print ("Total Sum is:" , sum)

def get_sum(numb):
    p = 0
    n = 1
    sum = 0
    while n < numb:
        c = p + n
        if (c%2 == 0):
            sum = sum + c
        p = n
        n = c       
    return sum

if __name__== "__main__":
    main()
